---
parser: babel-eslint
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true
env:
  browser: true
  amd: true
  es6: true
  node: true
  mocha: true
globals:
  __DEVELOPMENT__: false
  __DEVTOOLS__: false
  expect: false
extends:
  - airbnb

settings:
  import/resolver:
    webpack:
      config: webpack/webpack.dev.js
rules:
  max-len:
    - off
  comma-dangle:
    - off
  no-constant-condition:
    - warn
    - checkLoops: false
  no-unused-vars:
    - warn
  no-plusplus:
    - off
  react/prefer-stateless-function:
    - 0
  import/first:
    - warn
  react/no-unused-prop-types:
    - warn
  no-useless-constructor:
    - off
  no-prototype-builtins:
    - warn
  camelcase:
    - warn

  react/jsx-filename-extension: 'off'
  react/jsx-wrap-multilines: 'off'
  react/forbid-prop-types: 'off'
  react/no-multi-comp: 'off'

  jsx-a11y/href-no-hash: 'off'

  arrow-parens:
    - warn
    - as-needed
    - requireForBlockBody: true
  

